apiVersion: v1
kind: Secret
metadata:
  name: omni-inventory-secret
  namespace: omni-inventory
  labels:
    app.kubernetes.io/name: omni-inventory
    app.kubernetes.io/part-of: omni-inventory
type: Opaque
stringData:
  POSTGRES_PASSWORD: change-me
  DATABASE_URL: postgresql://postgres:change-me@omni-postgres:5432/inventory_db
  AUTH0_CLIENT_SECRET: replace-with-real-secret
